# Generated by Django 3.2.12 on 2022-08-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='certificates')),
                ('certname', models.CharField(max_length=50)),
                ('tagone', models.CharField(max_length=20)),
                ('tagtwo', models.CharField(max_length=20)),
            ],
        ),
    ]
