# Generated by Django 3.2.12 on 2022-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_alter_certification_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='img',
            field=models.FileField(upload_to='certificates'),
        ),
    ]
